### ISSUE TITLE
Browser version doesn't work

### ISSUE THREAD

**Issue by JoshuaDeClercq** [nolanlawson/pouchdb-full-sync#6]
I included both files (pouchdb 5.4.4 and pouchdb.full-sync 1.0.3 ) in a browser as stated:

> In the browser  To use this plugin in the browser, include it after pouchdb.js in your HTML page: `<scripts rc="pouchdb.js"></script><script src="pouchdb.full-sync.js"></script>`

but i get the following error

> TypeError: db.fullySync is not a function(…)

**Comment by nolanlawson** [comment]
thanks for reporting, fixed in a37773bb3185d6a70fab38610fccbec7e0765948

**Comment by nolanlawson** [comment]
published as 1.0.4

**Comment by JoshuaDeClercq** [comment]
thanks for the quick response!
but now i get the following issue:

> TypeError: PouchConstructor is not a constructor(…)
