### ISSUE TITLE
Browser version doesn't work (2)

### ISSUE THREAD

**Issue by JoshuaDeClercq** [nolanlawson/pouchdb-full-sync#8]
I included both files ( pouchdb 5.4.4 and pouchdb.full-sync 1.0.4 ) in a browser as stated:

> In the browser To use this plugin in the browser, include it after pouchdb.js in your HTML page: 
`<scripts rc="pouchdb.js"></script><script src="pouchdb.full-sync.js"></script>`

but i get the following error

> TypeError: PouchConstructor is not a constructor(…)

test source : https://gist.github.com/JoshuaDeClercq/da37000fd700278e50a680232eb8b22d

In app.js switch between line 139/140 to switch between normal sync() en fullySync()

**Comment by nolanlawson** [comment]
Thanks for the test case! Using the test case I was able to figure out the issue; it's fixed in v1.0.5.
